### PR TITLE
`nonEmptyArray`: change output type from `Array` to `NonEmptyArray`

### PR DESCRIPTION
**Pull request by OliverJAsh**
Needed to allow things like this—otherwise we get a type error:

```ts
nonEmptyArray(t.unknown).pipe(nonEmptyArray(t.unknown))
```

My real world use case:

```ts
declare const StringArrayFromString: t.Type<NEA.NonEmptyArray<string>, string, unknown>
declare const XpIdAndVariantFromString: t.Type<[string, string], string, unknown>;
StringArrayFromString.pipe(t.nonEmptyArray(XpIdAndVariantFromString))
```

### CODE REVIEW

**Comment by OliverJAsh** [comment]
@gcanti I'm not sure why the build is failing. I can't reproduce it locally and this doesn't seem to be due to a change in this PR.

**Comment by gcanti** [comment]
@OliverJAsh try upgrading to latest `io-ts` (https://github.com/gcanti/io-ts/releases/tag/2.2.18)

```diff
-    nea => arr.encode(nea)
+    identity
```

This will introduce a bug, you must encode each elements (we should add a test for this, now is missing)

**Comment by gcanti** [comment]
> we should add a test for this

Something like

```diff
it('encode', () => {
  const T = nonEmptyArray(t.number)
  assert.deepStrictEqual(T.encode(cons(1, [2, 3])), [1, 2, 3])
  assert.deepStrictEqual(T.encode(cons(1, [])), [1])
+  const T2 = nonEmptyArray(NumberFromString)
+  assert.deepStrictEqual(T2.encode(cons(1, [])), ['1'])
})
```

**Comment by OliverJAsh** [comment]
Good catch, thanks: e83a18aa7f3dd1d9fa86aedbe81e0deb872b74c0

**Comment by OliverJAsh** [comment]
I was wondering why the types didn't catch this bug. If we change the types like so then it will correctly error if the wrong `encode` function is provided. WDYT?

```diff
diff --git a/src/nonEmptyArray.ts b/src/nonEmptyArray.ts
index 3453c9a..75c6bac 100644
--- a/src/nonEmptyArray.ts
+++ b/src/nonEmptyArray.ts
@@ -7,24 +7,24 @@ import { isNonEmpty } from 'fp-ts/lib/Array'
 import { pipe } from 'fp-ts/lib/pipeable'
 import { chain } from 'fp-ts/lib/Either'
 import { isNone } from 'fp-ts/lib/Option'
+import { identity } from 'fp-ts/lib/function'
 
 /**
  * @since 0.5.0
  */
-export interface NonEmptyArrayC<C extends t.Mixed>
-  extends t.Type<NonEmptyArray<t.TypeOf<C>>, NonEmptyArray<t.OutputOf<C>>, unknown> {}
+export interface NonEmptyArrayC<A, O> extends t.Type<NonEmptyArray<A>, NonEmptyArray<O>, unknown> {}
 
 /**
  * @since 0.5.0
  */
-export function nonEmptyArray<C extends t.Mixed>(
-  codec: C,
+export function nonEmptyArray<A, O>(
+  codec: t.Type<A, O, unknown>,
   name: string = `NonEmptyArray<${codec.name}>`
-): NonEmptyArrayC<C> {
+): NonEmptyArrayC<A, O> {
   const arr = t.array(codec)
   return new t.Type(
     name,
-    (u): u is NonEmptyArray<t.TypeOf<C>> => arr.is(u) && isNonEmpty(u),
+    (u): u is NonEmptyArray<A> => arr.is(u) && isNonEmpty(u),
     (u, c) =>
       pipe(
         arr.validate(u, c),
@@ -33,6 +33,6 @@ export function nonEmptyArray<C extends t.Mixed>(
           return isNone(onea) ? t.failure(u, c) : t.success(onea.value)
         })
       ),
-    map(codec.encode)
+    identity
   )
 }

```

**Comment by gcanti** [comment]
@OliverJAsh still failing

> try upgrading to latest io-ts (https://github.com/gcanti/io-ts/releases/tag/2.2.18)

TypeScript 4.7 / 4.8 broke `io-ts`

> I was wondering why the types didn't catch this bug

Yeah it's an old long story... I don't even remeber the details (/cc @sledorze) but basically it'a the price for allowing `C extends t.Mixed` in the definition of `NonEmptyArrayC` (but I may be wrong)

**Comment by OliverJAsh** [comment]
@gcanti Thanks, it's green now.

**Comment by gcanti** [comment]
@OliverJAsh released :+1:

**Pull request merged**
