### PR TITLE
fix createEitherFromJSON and createOptionFromJSON do not serialize co…

### LINKED ISSUE #15: createEitherFromJSON and createOptionFromJSON do not serialize correctly their underlying type
@gcanti  The title says it all, a PR will follow.

### PR DESCRIPTION
**Pull request by sledorze**
…rrectly their underlying type (fixes #15)

### CODE REVIEW

**Comment by gcanti** [comment]
Thanks Stéphane

**Comment by sledorze** [comment]
that's pure love Giulio!

**Comment by sledorze** [comment]
@gcanti thanks for the release!

**Comment by gcanti** [comment]
@sledorze about serialisations I'm working on a big improvement of io-ts, I'll send a PR asap

**Comment by sledorze** [comment]
@gcanti are you talking about performance or feature?

**Comment by gcanti** [comment]
Feature. Perfomance-wise the best improvement will be adding the `taggedUnion` combinator: my preliminary tests show great results.

**Comment by sledorze** [comment]
ok, keep me updated

**Pull request merged**
