### PR TITLE
feat: export each module's exports from the library entrypoint

### LINKED ISSUE #129: Export all types from index
## 🚀 Feature request

I'd like to be able to import `io-ts-types` once and have all the codecs/combinators, like Ramda. AFAIK right now each thing must be imported from its own file.

### Current Behavior

```typescript
import { fromNullable } from 'io-ts-types/lib/fromNullable';
import { DateFromISOString } from 'io-ts-types/lib/DateFromISOString';
```

### Desired Behavior

```typescript
import { fromNullable, DateFromISOString } from 'io-ts-types/lib';
```

### Suggested Solution

Add index files with re-exports.

### Who does this impact? Who is this for?

All users except those who import individual files for bundle size reasons.

Bundle size is not a concern on NodeJS, where `io-ts` can be used for validation.

### Describe alternatives you've considered

It would be ideal to just `import 'io-ts-types'`. Not sure if that's possible.

### Your environment

| Software    | Version(s) |
| ----------- | ---------- |
| fp-ts       |    2.6.1   |
| io-ts       |    2.2.3   |
| io-ts-types |    0.5.6   |
| TypeScript  |    3.9.3   |

### PR DESCRIPTION
**Pull request by waynevanson**
I noticed that `package.json` updated automatically.
Would you like to keep this change or have it reversed?

Do we need tests to check that `index.ts` is exporting the correct modules?
If so, I'd recommend that the tests import their from `index.ts` rather than from the source.

closes #129

### CODE REVIEW

**Comment by gcanti** [comment]
> Would you like to keep this change or have it reversed?

Let's keep it

> I'd recommend that the tests import their from index.ts rather than from the source

Good idea

**Comment by waynevanson** [comment]
@gcanti Changed the imports for dtslint tests and runtime tests.

**Comment by waynevanson** [comment]
Would you like these condensed down into a single commit?

**Comment by gcanti** [comment]
> Would you like these condensed down into a single commit?

No thanks, LGTM

**Comment by gcanti** [comment]
@waynevanson v0.5.8 released, thanks!

**Pull request merged**
