### PR TITLE
UUID type added

### PR DESCRIPTION
**Pull request by mlegenhausen**
Really common datatype when working with databases.

### CODE REVIEW

**Comment by gcanti** [comment]
how do you feel about moving `UUID.ts` to a `string` folder?

**Comment by mlegenhausen** [comment]
Sure!

**Comment by mlegenhausen** [comment]
Done

**Comment by gcanti** [comment]
Looks like travis is failing due to https://github.com/facebook/jest/issues/6766
We could try this fix https://github.com/facebook/jest/issues/6766#issuecomment-408381957

**Comment by mlegenhausen** [comment]
Jest fix added.

**Comment by gcanti** [comment]
Thanks @mlegenhausen

**Pull request merged**
