### PR TITLE
DateType added

### PR DESCRIPTION
**Pull request by mlegenhausen**
@gcanti how do you like the naming?

### CODE REVIEW

**Comment by gcanti** [comment]
The convention so far is capitalize (`DateFromISOString`, `DateFromNumber`, etc...) so I'd go for `Date`

**Comment by mlegenhausen** [comment]
@gcanti This results in a collision with the buildin `Date` type. Using something like `window.Date` for the instance check would result in incompatiblity with non browser environments.

Maybe something like `Date_` to prevent the collision?

**Comment by gcanti** [comment]
Ah right. Then let's keep it as it is

**Comment by mlegenhausen** [comment]
Then from my side we could merge?

**Comment by gcanti** [comment]
Thanks @mlegenhausen

**Pull request merged**
