### PR TITLE
Bug Fix: upstream inference bug using createOptionFromNullable in a nested runtime type, closes #67

### LINKED ISSUE #67: OptionFromNullableType output type is any
Hi,

I noticed that the output type of `OptionFromNullable` Type  is `any`. What is the rational for this?
For example if I have a runtime type
```
const status = t.type({
        lastViewed: createOptionFromNullable(DateFromISOString),
})
```
It implies that the contract I'm expecting is 
```
{
 lastViewed: string | null
}
```

But the output type, which in some sense symbolized that contract I'm suppose to send back (and normally also receive) , getting by 
```
type status_output= t.OutputOf<typeof status>;
```
will be:
```
{
 lastViewed: any
}
````

Thanks!

### PR DESCRIPTION
**Pull request by gcanti**
@sledorze what do you think about this pattern?

```ts
export const createOptionFromNullable = <A, O>(
  type: t.Type<A, O, t.mixed>,
  name: string = `Option<${type.name}>`
): OptionFromNullableType<typeof type, Option<A>, O | null, t.mixed>
```

### CODE REVIEW

**Comment by gcanti** [comment]
@sledorze just added dtslint, from now on we can write type-level regression tests.

> I'm pretty sure we were using indirect typings of A and O (basically deduced from type's type) to prevent inferring to '{}' or 'any' in some cases

Searching the issues I found https://github.com/gcanti/io-ts-types/issues/18

I don't understand your last comment though

> Note the it maps to different types which may be useful in some contexte; for instance if you would return a type projection that's not part of the function type parameters and is dependent of the actual T type; in that case the second solution is not applicable

I think we should switch to a simpler signature, the current one is pretty weird (other than buggy)

```ts
//    RT and A are mutually referenced --v------------------------v
export const createOptionFromNullable = <RT extends t.Type<A, O>, A = t.TypeOf<RT>, O = t.OutputOf<RT>>(
  type: RT,
  name: string = `Option<${type.name}>`
): OptionFromNullableType<RT, Option<A>, O | null, t.mixed>
```

The signature contained in this PR however looks neat and safe

**Comment by sledorze** [comment]
@gcanti sorry I missed your request for clarifications.
Anyway it has been merged, I may come back to that when/if I find an inference issue.

**Comment by gcanti** [comment]
@sledorze nevermind, after additional tests it doesn't work as I want

```ts
const X = createOptionFromNullable(t.string)
```

`X` is inferred as 

```ts
OptionFromNullableType<t.Type<string, string, t.mixed>, Option<string>, string | null, t.mixed>
```

I want 

```ts
OptionFromNullableType<t.StringType, Option<string>, string | null, t.mixed>
```

I'll switch back to `io-ts` pattern

```ts
<RT extends t.Mixed>(
  type: RT,
  name?: string
) => OptionFromNullableType<
  RT,
  Option<t.TypeOf<RT>>,
  t.OutputOf<RT> | null,
  t.mixed
>
```

which never caused any inference issue

**Comment by sledorze** [comment]
I wonder which one is preferable

```typescript
Option<t.TypeOf<RT>>
```
or

```typescript
Option<t.TypeOf<typeof type>>
```

**Pull request merged**
